### ISSUE TITLE
Theme base Routing

### ISSUE THREAD

**Issue by justinlevi** [drupal-graphql/graphql-twig#13]
Running into an odd behavior with the routes defined in my theme info.yml file. I feel like I might be missing something simple, but the routes don't seem to be loading as I have them defined. 

Here's what I have defined in my `[THEME].info.yml` file

```
routes:
  home:
    path: "/home"
    title: "MY TITLE HERE"

```

Here's what my `templates/home.html.twig` looks like:

```
<h1>HOME twig template</h1>
{% include '@storybook/01-base/02-atoms/title.twig' with { title: 'HOME THEME BASED ROUTING' } %}
```

This template never gets loaded when I browse to the home path. 

Any ideas?

**Comment by justinlevi** [comment]
Just a quick update that I was able to get an `about` route to work

```
routes:
  about:
    path: "/about"
    title: "HERE'S A TITLE"

```

Still not sure why my /home route wouldn't work though
